version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: account
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: